### ISSUE TITLE
Errors when attempting to create entry

### ISSUE THREAD

**Issue by brianlmoon** [samihsoylu/journal#20]
I am seeing the following error when trying to go to the /entry/create and /template URLs. 

```
 Fatal error: require(): Failed opening required '/var/www/private/cache/database/proxy/__CG__AppDatabaseModelCategory.php'
(include_path='.:/usr/share/php') in /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 187
```
I can create categories and users. I checked and that directory is empty. I am not sure what is supposed to create that file. I even deleted everything and did the full reinstall again. Same error.

**Comment by samihsoylu** [comment]
Hi @brianlmoon 

This is very odd that you have issues out of the box. From the command line can you please try the following:
```
vendor/bin/doctrine orm:generate-proxies
```

Let me know how it goes.

**Comment by brianlmoon** [comment]
That got everything working. The permissions on private/cache directory were fine. The proxies just didn't get generated for some reason.

**Comment by samihsoylu** [comment]
I am glad to hear that regenerating the proxies worked out well.

Pull request #21 includes a fix that will prevent the need to regenerate proxies all together. For now, I have updated the documentation to include generating the proxies as a step in the installation.

The pull request will be merged soon.
